Homework 1
AlexeyVasilenkoDev/Homework pull request #4
Opened 2022-07-04 20:05 UTC by AlexeyVasilenkoDev

2022-07-04 20:05 UTC, AlexeyVasilenkoDev commented
Decorators homework

2022-07-05 07:51 UTC, Seclorum12 requested changes
Загалом - нормально. Перероби, будь ласка, `lfu`

2022-07-05 07:51 UTC, Seclorum12 commented on homework1/homework1.py
> +import psutil
Ліби не у Pipfile

2022-07-05 07:51 UTC, Seclorum12 commented on homework1/homework1.py
> +fetch_url('https://stackoverflow.com')
Виклик треба обертати у конструкцію `__main__`. Без неї функціі викликаються при імпорті.

2022-07-05 07:51 UTC, Seclorum12 commented on homework1/homework1.py
> +        if args[0] in cache.keys():
Декоратор не універсальний, він використовує аргумент як ключ, а треба вікористовувати всі параметри та іменовані параметри як ключ. Це можна зробити декількома способами, але є проста конструкція, яка обертає всі параметри в тапл. Коли тапл використовується як ключ словника, то він під капотом хешується (прймає вид строки). Пошукай як вікористати `*args, **kwargs` ключом слоника.

2022-07-05 07:51 UTC, Seclorum12 commented on homework1/homework1.py
> +        f(*args, **kwargs)
Декорована функція визивається, але як ти повернеш ії результат? Зараз повертається дікт, а не результат функції.

2022-07-05 07:51 UTC, Seclorum12 commented on homework1/homework1.py
> +        process = psutil.Process(os.getpid())
StackOverflow дуже гарний ресурс, але його треба звіряти з документацією :smile: 
Якщо вірити докуметації, то `psutil.Process(os.getpid())` є теж саме, що `psutil.Process(). :smile:

2022-07-05 07:51 UTC, Seclorum12 commented on homework1/homework1.py
> +        memory_before = process.memory_info()[0]
Якщо є можливість, то краже використовувати імена, замість індексів. У данному випадку `process.memory_info().rss`

2022-07-05 11:02 UTC, Seclorum12 requested changes

2022-07-05 11:02 UTC, Seclorum12 commented on homework1/homework1.py
> +@lfu
Спробуй передати тут якійсь аргументи. (З реалізацію декоратора з однією вкладенностю ти не можешь передати аргументи)

2022-07-05 11:02 UTC, Seclorum12 commented on homework1/homework1.py
> +        return my_func, result
Потрібно щоб повертався результат визову функції. Зараз кожен виклик виконується обернута функція, а потрібно щоб вона викликалась тільки з новими аргументами.
Ти дуже близко до рішення, але не вистачає декількох моментів.
Підказка:
- Тобі треба ще одну вкладенність
- Тобі потрібен словник з ключом `[cache_key]['conunter']` та '`[cache_key]['result']`

2022-07-05 11:06 UTC, Seclorum12 commented
Якщо не знайдеш правильне рішення, можеш написати мені у ТГ

2022-07-06 18:35 UTC, merged